name: Descarga

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 6' # A las 00:00 del sábado

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: AUTOMATIZACIÓN
        run: |
          echo "¡Hola de nuevo!1" >> $GITHUB_WORKSPACE/archivo.txt

      # Persistir archivo.txt en el sistema de archivos del runner
      - name: Persistir archivo.txt
        if: always()
        run: mv $GITHUB_WORKSPACE/archivo.txt $RUNNER_WORKSPACE/archivo.txt

  build2:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      # Copiar archivo.txt desde el sistema de archivos del runner
      - name: Copiar archivo.txt
        run: cp $RUNNER_WORKSPACE/archivo.txt $GITHUB_WORKSPACE/archivo_copiado.txt

      - name: Commit y push cambios
        uses: stefanzweifel/git-auto-commit-action@v2
        with:
          commit_message: "Actualizacion"
          branch: main
          commit_user_name: Actions Bot
          commit_user_email: lmonsalve22@gmail.com
          commit_author: DataIntelligence BOT <lmonsalve22@gmail.com>
          push_options: '--force'
