name: Descarga

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 6' # A las 00:00 del sábado

jobs:
  common:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  build1:
    needs: common
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar pruebas para job1
        run: python test.py job4

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: shared
          path: job4.csv

  build2:
    needs: common
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar pruebas para job2
        run: python test.py job5

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: shared
          path: job5.csv

  build3:
    needs: common
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar pruebas para job3
        run: python test.py job6

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: shared
          path: job6.csv

  unir:
    needs: [build1, build2, build3]
    runs-on: ubuntu-latest
    steps:
      - name: Descargar artefactos
        uses: actions/download-artifact@v2
        with:
          name: shared-files
          path: shared

      - name: Commit y push cambios
        uses: stefanzweifel/git-auto-commit-action@v2
        with:
          commit_message: "Actualizacion"
          branch: main
          commit_user_name: Actions Bot
          commit_user_email: lmonsalve22@gmail.com
          commit_author: DataIntelligence BOT <lmonsalve22@gmail.com>
          push_options: '--force'

