name: Share Files Between Jobs

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create file
        run: echo "Hello from Job 1" > shared_file.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: shared-files
          path: shared_file.txt

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: shared-files
          path: shared

      - name: Print shared file content
        run: cat shared/shared_file.txt

